### ISSUE TITLE
base motif fractal article widget looks like poop

### ISSUE THREAD

**Issue by anematode** [Nichodon/nichodon.github.io#157]
not sure what you did Brandon but https://www.moomath.com/articles/0003/

**Comment by Nichodon** [comment]
Problem with putting what should be on two canvases on one canvas. Very little flexibility for responsiveness. I will make a quick fix but maybe in the future I'll try to separate the two graphs.

**Comment by Nichodon** [comment]
The two-graph canvas is still too wide, but the standard GUI styles have been added. So it no longer looks like feces! 😀
