### ISSUE TITLE
Program parser is very buggy

### ISSUE THREAD

**Issue by anematode** [Nichodon/nichodon.github.io#158]
https://moomath.com/programs/ Polyrhythm player is oddly indented, an extra article called "undefined" is present

**Comment by Nichodon** [comment]
Actually, the undefined is not a problem with the parser, it's because of @Maydoh1239 commit in #145.

**Comment by anematode** [comment]
lol that's funny
maybe we should make it ignore blank lines after all?

what's the indentation caused by?

**Comment by Nichodon** [comment]
Yeah, I'll make it more flexible. And I'll take a look at indents.
