### ISSUE TITLE
Use letter-spacing: 0px for most things

### ISSUE THREAD

**Issue by anematode** [Nichodon/nichodon.github.io#159]
Please use a small letter spacing and small line height for anything that's more than a sentence so that it's a little easier to read

**Comment by Nichodon** [comment]
I didn't notice but actually this is already done.

**Comment by anematode** [comment]
The line spacing is still wonky.
I’m also talking about the descriptions of articles and programs in /articles and /programs... they shouldn’t be so sparse either. In general the search pages are really TALL which is awkward, so we should cut down on line height and other space hoggera
