### ISSUE TITLE
Make status in /articles and /programs a little more natural

### ISSUE THREAD

**Issue by anematode** [Nichodon/nichodon.github.io#160]
Perhaps bold "Status"

**Comment by Nichodon** [comment]
Not sure what status is.

**Comment by anematode** [comment]
"This converter has one of the longest list of units on the internet. You can convert length, mass, area… or even CO2 Per Unit Volume!
Status: Support needed for units that have extra calculations in converting, for example temperature."

**Comment by Nichodon** [comment]
Oh. Didn't see that because I was looking at articles.

**Comment by anematode** [comment]
lol srry
