### ISSUE TITLE
Inconsistent use of <b>, <strong>, <i>, <em>

### ISSUE THREAD

**Issue by Nichodon** [Nichodon/nichodon.github.io#165]
Better to never use b and i, though there are instances of them.

**Comment by Nichodon** [comment]
@anematode help fix as well. Maybe a program in the future for global find and replace.

**Comment by anematode** [comment]
What about usage of <i> in articles?

**Comment by Nichodon** [comment]
Use <em> instead.

**Comment by anematode** [comment]
What’s instead

**Comment by Nichodon** [comment]
Arg. I typed "em" as a tag, and MD auto-italic instead. Use the "em" tag.

**Comment by Nichodon** [comment]
Still a problem in CPP book.
