### ISSUE TITLE
Sort out what the goto article is

### ISSUE THREAD

**Issue by Nichodon** [Nichodon/nichodon.github.io#172]
From #162, this is a bit hard to convert because of the external widgets.

**Comment by anematode** [comment]
Brandon... I don't think we can have articles in pure textual format

**Comment by anematode** [comment]
We need to have some HTML for things like programs within the article

**Comment by Nichodon** [comment]
Um. You **can** have HTML in the articles. Look at any of the four `article.txt`. You will find a whole lot of raw HTML. Nevertheless, I have opened #173.
