### ISSUE TITLE
AdBlock doesn't like Moomath

### ISSUE THREAD

**Issue by anematode** [Nichodon/nichodon.github.io#178]
https://www.moomath.com/programs/ does not work because of a blocked Cross Site request to nichodon.github.io from moomath.com. https://moomath.com/articles/ is similarly affected.

Solutions:

1. Change link to moomath.com, but then nichodon.github.io won't work
2. Make link replaceable in build.sh

**Comment by Nichodon** [comment]
Keep in mind that [](https://www.moomath.com) is **not the same as** [](https://moomath.com).

**Comment by anematode** [comment]
ah it was because of an ad blocker

that might not be so desirable tho

**Comment by Nichodon** [comment]
Solution 1 is okay, no one should be going to https://nichodon.github.io anyway.

**Comment by anematode** [comment]
Fixed
