### ISSUE TITLE
Critical security issue

### ISSUE THREAD

**Issue by SheepTester** [Nichodon/nichodon.github.io#190]
![screenshot 2018-04-26 at 14 46 20](https://user-images.githubusercontent.com/22133785/39333702-adfba25c-4960-11e8-9095-db04878094bb.png)
Jupiter sphere behind the text on the index page doesn't recenter itself when the page is resized.

**Comment by anematode** [comment]
Critical security issue

**Comment by Nichodon** [comment]
Finally fixed, though my main concern is why you had inspect up in the first place. Also I hope your second tab does not apply to us.
