### ISSUE TITLE
Mapping the Plane with Matrices link broken

### ISSUE THREAD

**Issue by SheepTester** [Nichodon/nichodon.github.io#206]
Seems like it should be `map_plane` not `mat_plane`
https://github.com/Nichodon/nichodon.github.io/blob/7d574ce0e55f55221b59405bfa63349b08ff64bb/gatm/index.html#L149
https://github.com/Nichodon/nichodon.github.io/blob/7d574ce0e55f55221b59405bfa63349b08ff64bb/gatm/index.html#L180

**Comment by anematode** [comment]
Fixed in #207 !
